apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  labels:
    run: sj4
  name: sj4
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
    spec:
      completion: 5
      Parallelism: 1
      activeDeadlineSeconds: 20
      template:
        metadata:
          labels:
            run: sj4
        spec:
          containers:
          - args:
            - sleep
            - "10"
            image: busybox
            imagePullPolicy: Always
            name: sj4
            resources: {}
          restartPolicy: Never
  schedule: '*/1 * * * *'
  suspend: false

