apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  labels:
    run: sj3
  name: sj3
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
    spec:
      completion: 5
      Parallelism: 1
      activeDeadlineSeconds: 5
      template:
        metadata:
          labels:
            run: sj3
        spec:
          containers:
          - args:
            - sleep
            - "10"
            image: busybox
            imagePullPolicy: Always
            name: sj3
            resources: {}
          restartPolicy: Never
  schedule: '*/1 * * * *'
  suspend: false

